C     GENERAL ELECTRIC ARC FURNACE MATERIAL AND HEAT BALANCE.
C
C     THIS IS A CONFIGURABLE FIXED-FORM FORTRAN PROGRAM.  IT READS
C     STREAM COMPOSITIONS, FIXED MASSES, UNKNOWN MASSES, SOFT MASS
C     TARGETS, SENSIBLE-HEAT COEFFICIENTS, AND GENERAL HEAT TERMS.
C
C     SIGN CONVENTION FOR MATERIAL BALANCE:
C       SIDE =  1  INPUT STREAM
C       SIDE = -1  OUTPUT STREAM
C
C     SIGN CONVENTION FOR HEAT BALANCE:
C       POSITIVE KWH = HEAT DEMAND OR LOSS
C       NEGATIVE KWH = HEAT SUPPLY OR EXOTHERMIC CREDIT
C
C     NOTATION USED IN THE SOURCE:
C       N...   = COUNTS OR INDICES
C       M...   = MEASURED/TARGET MASS DATA
C       MASS   = STREAM MASS, KG
C       FRAC   = COMPONENT MASS FRACTION
C       A,B,X  = LEAST-SQUARES SYSTEM A*X = B
C       RES    = MATERIAL-BALANCE OR TARGET RESIDUAL, KG
C       H...   = HEAT-TERM DATA OR RESULTS
C       ...KWH = HEAT TERMS REPORTED IN KWH

      PROGRAM GEAFBAL
      IMPLICIT NONE

      INTEGER MAXE,MAXS,MAXU,MAXQ,MAXT
      PARAMETER (MAXE=20,MAXS=60,MAXU=40,MAXQ=140,MAXT=120)

      INTEGER IU,IO,IEOF,NELEM,NSTR,NMEAS,NHTERM
      INTEGER I,J,K,U,NU,NEQ,INFO,RANK,DOF,REDUN
      INTEGER SIDE(MAXS),FIXED(MAXS),UINDEX(MAXS)
      INTEGER MSTR(MAXQ),HSTR(MAXT)

      CHARACTER*1024 LINE
      CHARACTER*120 TITLE
      CHARACTER*16 ENAME(MAXE),SNAME(MAXS)
      CHARACTER*16 MNAME(MAXQ),HNAME(MAXT),EQNAME(MAXQ)

      DOUBLE PRECISION EWT(MAXE),MASS(MAXS),HSGN(MAXS)
      DOUBLE PRECISION TEMP(MAXS),HA(MAXS),HB(MAXS)
      DOUBLE PRECISION HC(MAXS),HD(MAXS),FRAC(MAXS,MAXE)
      DOUBLE PRECISION MTARG(MAXQ),MWT(MAXQ)
      DOUBLE PRECISION HFACT(MAXT),HCOEF(MAXT),HCONST(MAXT)
      DOUBLE PRECISION A(MAXQ,MAXU),B(MAXQ),WEQ(MAXQ)
      DOUBLE PRECISION X(MAXU),RES(MAXQ),SHKWH(MAXS)
      DOUBLE PRECISION HKWH(MAXT)
      DOUBLE PRECISION C,RHS,CALC,WRES,SSE,RMS
      DOUBLE PRECISION DH,SENS,THTERM,HTOTAL,FSUM,OMASS,UNTR
      DOUBLE PRECISION TUNTR
      DOUBLE PRECISION ZERO,CONV

      ZERO=0.0D0
      CONV=3.6D6
      IU=55
      IO=66

      OPEN(IU,FILE='general_eaf_input.txt',STATUS='OLD')
      OPEN(IO,FILE='general_eaf_output.txt')

C     READ TITLE.
      CALL GETREC(IU,LINE,IEOF)
      IF (IEOF.NE.0) STOP 'EMPTY INPUT FILE'
      TITLE=LINE(1:120)

C     READ CONSERVED COMPONENTS OR ELEMENTS.
      CALL GETREC(IU,LINE,IEOF)
      READ(LINE,*,ERR=900) NELEM
      IF (NELEM.LE.0 .OR. NELEM.GT.MAXE) STOP 'BAD NELEM'

      DO 20 J=1,NELEM
         CALL GETREC(IU,LINE,IEOF)
         READ(LINE,*,ERR=901) ENAME(J),EWT(J)
   20 CONTINUE

C     READ STREAMS.
      CALL GETREC(IU,LINE,IEOF)
      READ(LINE,*,ERR=902) NSTR
      IF (NSTR.LE.0 .OR. NSTR.GT.MAXS) STOP 'BAD NSTREAM'

      DO 40 I=1,NSTR
         CALL GETREC(IU,LINE,IEOF)
         READ(LINE,*,ERR=903) SNAME(I),SIDE(I),FIXED(I),MASS(I),
     &        HSGN(I),TEMP(I),HA(I),HB(I),HC(I),HD(I),
     &        (FRAC(I,J),J=1,NELEM)
         UINDEX(I)=0
         IF (SIDE(I).NE.1 .AND. SIDE(I).NE.-1) STOP 'BAD SIDE'
         IF (FIXED(I).NE.0 .AND. FIXED(I).NE.1) STOP 'BAD FIXED'
   40 CONTINUE

C     READ SOFT MASS TARGETS OR MEASUREMENTS.
      CALL GETREC(IU,LINE,IEOF)
      READ(LINE,*,ERR=904) NMEAS
      IF (NMEAS.LT.0 .OR. NMEAS.GT.MAXQ) STOP 'BAD NMEAS'

      DO 50 K=1,NMEAS
         CALL GETREC(IU,LINE,IEOF)
         READ(LINE,*,ERR=905) MNAME(K),MSTR(K),MTARG(K),MWT(K)
         IF (MSTR(K).LT.1 .OR. MSTR(K).GT.NSTR) STOP 'BAD MEAS STR'
   50 CONTINUE

C     READ USER HEAT TERMS.
      CALL GETREC(IU,LINE,IEOF)
      READ(LINE,*,ERR=906) NHTERM
      IF (NHTERM.LT.0 .OR. NHTERM.GT.MAXT) STOP 'BAD NHTERM'

      DO 60 K=1,NHTERM
         CALL GETREC(IU,LINE,IEOF)
         READ(LINE,*,ERR=907) HNAME(K),HSTR(K),HFACT(K),
     &        HCOEF(K),HCONST(K)
         IF (HSTR(K).LT.0 .OR. HSTR(K).GT.NSTR) STOP 'BAD HEAT STR'
   60 CONTINUE

C     MAP UNKNOWN STREAM MASSES TO SOLVER VARIABLES.
      NU=0
      DO 70 I=1,NSTR
         IF (FIXED(I).EQ.0) THEN
            NU=NU+1
            IF (NU.GT.MAXU) STOP 'TOO MANY UNKNOWNS'
            UINDEX(I)=NU
         ENDIF
   70 CONTINUE

C     CLEAR EQUATION MATRIX.
      DO 90 K=1,MAXQ
         B(K)=ZERO
         WEQ(K)=ZERO
         RES(K)=ZERO
         EQNAME(K)=' '
         DO 80 U=1,MAXU
            A(K,U)=ZERO
   80    CONTINUE
   90 CONTINUE

C     ELEMENT OR COMPONENT BALANCE EQUATIONS.
      NEQ=0
      DO 130 J=1,NELEM
         NEQ=NEQ+1
         IF (NEQ.GT.MAXQ) STOP 'TOO MANY EQUATIONS'
         EQNAME(NEQ)=ENAME(J)
         RHS=ZERO
         DO 120 I=1,NSTR
            C=DBLE(SIDE(I))*FRAC(I,J)
            IF (FIXED(I).EQ.0) THEN
               U=UINDEX(I)
               A(NEQ,U)=A(NEQ,U)+C
            ELSE
               RHS=RHS-C*MASS(I)
            ENDIF
  120    CONTINUE
         B(NEQ)=RHS
         WEQ(NEQ)=EWT(J)
  130 CONTINUE

C     SOFT STREAM MASS MEASUREMENTS OR TARGETS.
      DO 150 K=1,NMEAS
         IF (FIXED(MSTR(K)).EQ.0) THEN
            NEQ=NEQ+1
            IF (NEQ.GT.MAXQ) STOP 'TOO MANY EQUATIONS'
            EQNAME(NEQ)=MNAME(K)
            U=UINDEX(MSTR(K))
            A(NEQ,U)=1.0D0
            B(NEQ)=MTARG(K)
            WEQ(NEQ)=MWT(K)
         ENDIF
  150 CONTINUE

C     SOLVE WEIGHTED LEAST SQUARES.
      CALL MATRANK(NEQ,NU,A,WEQ,RANK)
      DOF=NU-RANK
      REDUN=NEQ-RANK

      IF (NU.GT.0) THEN
         CALL WLSOLVE(NEQ,NU,A,B,WEQ,X,INFO)
         IF (INFO.NE.0) THEN
            WRITE(IO,*) 'LEAST-SQUARES SOLVE FAILED, INFO=',INFO
            STOP 'SOLVE FAILED'
         ENDIF

         DO 160 I=1,NSTR
            IF (FIXED(I).EQ.0) MASS(I)=X(UINDEX(I))
  160    CONTINUE
      ENDIF

C     COMPUTE RESIDUALS FOR THE SOLVED EQUATIONS.
      SSE=ZERO
      DO 190 K=1,NEQ
         CALC=ZERO
         DO 180 U=1,NU
            CALC=CALC+A(K,U)*X(U)
  180    CONTINUE
         RES(K)=CALC-B(K)
         WRES=WEQ(K)*RES(K)
         SSE=SSE+WRES*WRES
  190 CONTINUE
      IF (NEQ.GT.0) THEN
         RMS=DSQRT(SSE/DBLE(NEQ))
      ELSE
         RMS=ZERO
      ENDIF

C     STREAM SENSIBLE HEAT.  USER SUPPLIES HSGN AND COEFFICIENTS.
      SENS=ZERO
      DO 210 I=1,NSTR
         DH=HA(I)+HB(I)*TEMP(I)+HC(I)*TEMP(I)*TEMP(I)
         IF (DABS(TEMP(I)).GT.1.0D-20) DH=DH+HD(I)/TEMP(I)
         SHKWH(I)=HSGN(I)*MASS(I)*DH/CONV
         SENS=SENS+SHKWH(I)
  210 CONTINUE

C     USER HEAT TERMS.  H = CONST_KWH + FACTOR*COEFF*MASS/3.6E6.
      THTERM=ZERO
      DO 220 K=1,NHTERM
         HKWH(K)=HCONST(K)
         IF (HSTR(K).GT.0) THEN
            HKWH(K)=HKWH(K)+HFACT(K)*HCOEF(K)
     &              *MASS(HSTR(K))/CONV
         ENDIF
         THTERM=THTERM+HKWH(K)
  220 CONTINUE

      HTOTAL=SENS+THTERM

C     WRITE REPORT.
      WRITE(IO,*) 'GENERAL EAF MATERIAL AND HEAT BALANCE'
      WRITE(IO,*) TITLE
      WRITE(IO,*)
      WRITE(IO,*) 'COUNTS'
      WRITE(IO,*) ' COMPONENTS/ELEMENTS',NELEM
      WRITE(IO,*) ' STREAMS',NSTR
      WRITE(IO,*) ' UNKNOWN STREAM MASSES',NU
      WRITE(IO,*) ' COMPONENT BALANCE EQUATIONS',NELEM
      WRITE(IO,*) ' SOFT TARGET EQUATIONS',NMEAS
      WRITE(IO,*) ' LEAST-SQUARES EQUATIONS',NEQ
      WRITE(IO,*) ' WEIGHTED MATRIX RANK',RANK
      WRITE(IO,*) ' DEGREES OF FREEDOM AFTER RANK TEST',DOF
      WRITE(IO,*) ' REDUNDANT/EXTRA EQUATIONS AFTER RANK TEST',REDUN
      WRITE(IO,*)

      WRITE(IO,*) 'STREAM MASSES, KG'
      WRITE(IO,*) 'ID NAME SIDE FIXED MASS FRACSUM UNTRACKED_KG'
      OMASS=ZERO
      TUNTR=ZERO
      DO 240 I=1,NSTR
         FSUM=ZERO
         DO 230 J=1,NELEM
            FSUM=FSUM+FRAC(I,J)
  230    CONTINUE
         UNTR=MASS(I)*(1.0D0-FSUM)
         OMASS=OMASS+DBLE(SIDE(I))*MASS(I)
         TUNTR=TUNTR+DBLE(SIDE(I))*UNTR
         WRITE(IO,*) I,SNAME(I),SIDE(I),FIXED(I),MASS(I),FSUM,
     &        UNTR
  240 CONTINUE
      WRITE(IO,*) 'OVERALL STREAM MASS RESIDUAL, KG',OMASS
      WRITE(IO,*) 'SIGNED UNTRACKED MASS RESIDUAL, KG',TUNTR
      WRITE(IO,*)

      WRITE(IO,*) 'STREAM DIAGNOSTICS'
      DO 245 I=1,NSTR
         FSUM=ZERO
         DO 243 J=1,NELEM
            FSUM=FSUM+FRAC(I,J)
  243    CONTINUE
         IF (DABS(FSUM-1.0D0).GT.1.0D-4) THEN
            WRITE(IO,*) 'FRACTION SUM WARNING',I,SNAME(I),FSUM
         ENDIF
         IF (MASS(I).LT.-1.0D-8) THEN
            WRITE(IO,*) 'NEGATIVE MASS WARNING',I,SNAME(I),MASS(I)
         ENDIF
  245 CONTINUE
      WRITE(IO,*)

      WRITE(IO,*) 'STREAM COMPOSITIONS, MASS FRACTIONS'
      DO 260 I=1,NSTR
         WRITE(IO,*) 'STREAM',I,SNAME(I)
         WRITE(IO,*) (FRAC(I,J),J=1,NELEM)
  260 CONTINUE
      WRITE(IO,*)

      WRITE(IO,*) 'BALANCE RESIDUALS, KG'
      WRITE(IO,*) 'NAME RESIDUAL WEIGHT WEIGHTED_RESIDUAL'
      DO 270 K=1,NEQ
         WRITE(IO,*) EQNAME(K),RES(K),WEQ(K),WEQ(K)*RES(K)
  270 CONTINUE
      WRITE(IO,*) 'WEIGHTED RMS RESIDUAL',RMS
      WRITE(IO,*)

      WRITE(IO,*) 'SENSIBLE HEAT BY STREAM, KWH'
      WRITE(IO,*) 'NAME HSGN TEMP_K SENSIBLE_KWH'
      DO 280 I=1,NSTR
         WRITE(IO,*) SNAME(I),HSGN(I),TEMP(I),SHKWH(I)
  280 CONTINUE
      WRITE(IO,*) 'TOTAL SENSIBLE HEAT, KWH',SENS
      WRITE(IO,*)

      WRITE(IO,*) 'USER HEAT TERMS, KWH'
      WRITE(IO,*) 'NAME STREAM FACTOR COEFF_J_PER_KG CONST_KWH KWH'
      DO 290 K=1,NHTERM
         WRITE(IO,*) HNAME(K),HSTR(K),HFACT(K),HCOEF(K),
     &        HCONST(K),HKWH(K)
  290 CONTINUE
      WRITE(IO,*) 'TOTAL USER HEAT TERMS, KWH',THTERM
      WRITE(IO,*)

      WRITE(IO,*) 'NET HEAT BALANCE, KWH',HTOTAL
      WRITE(IO,*) 'POSITIVE MEANS ADDITIONAL HEAT DEMAND'
      WRITE(IO,*) 'NEGATIVE MEANS NET HEAT SURPLUS'

      CLOSE(IU)
      CLOSE(IO)
      STOP

  900 STOP 'READ ERROR: NELEM'
  901 STOP 'READ ERROR: ELEMENT LINE'
  902 STOP 'READ ERROR: NSTREAM'
  903 STOP 'READ ERROR: STREAM LINE'
  904 STOP 'READ ERROR: NMEAS'
  905 STOP 'READ ERROR: MEASUREMENT LINE'
  906 STOP 'READ ERROR: NHTERM'
  907 STOP 'READ ERROR: HEAT TERM LINE'
      END

C=======================================================================
C     READ NEXT NONBLANK, NONCOMMENT RECORD.  COMMENT LINES START WITH
C     '#' OR '!'.  THE FULL LINE IS RETURNED FOR INTERNAL LIST READS.
C=======================================================================
      SUBROUTINE GETREC(IU,LINE,IEOF)
      IMPLICIT NONE
      INTEGER IU,IEOF,L,I
      CHARACTER*(*) LINE
      CHARACTER*1 CH

      IEOF=0
   10 CONTINUE
      READ(IU,'(A)',END=90) LINE
      L=LEN(LINE)
      I=1
   20 IF (I.LE.L) THEN
         CH=LINE(I:I)
         IF (CH.EQ.' ' .OR. CH.EQ.CHAR(9)) THEN
            I=I+1
            GOTO 20
         ENDIF
      ENDIF

      IF (I.GT.L) GOTO 10
      CH=LINE(I:I)
      IF (CH.EQ.'#' .OR. CH.EQ.'!') GOTO 10
      RETURN

   90 IEOF=1
      LINE=' '
      RETURN
      END

C=======================================================================
C     MATRIX RANK ESTIMATE FOR THE WEIGHTED LEAST-SQUARES MATRIX.
C     THIS IS USED ONLY FOR DOF AND REDUNDANCY REPORTING.
C=======================================================================
      SUBROUTINE MATRANK(NEQ,NU,A,W,RANK)
      IMPLICIT NONE
      INTEGER MAXU,MAXQ
      PARAMETER (MAXU=40,MAXQ=140)
      INTEGER NEQ,NU,RANK,I,J,K,P,NCOL
      DOUBLE PRECISION A(MAXQ,MAXU),W(MAXQ),M(MAXQ,MAXU)
      DOUBLE PRECISION AMAX,TMP,FAC,TOL

      RANK=0
      IF (NEQ.LE.0 .OR. NU.LE.0) RETURN

      DO 20 I=1,NEQ
         DO 10 J=1,NU
            M(I,J)=W(I)*A(I,J)
   10    CONTINUE
   20 CONTINUE

      TOL=1.0D-10
      NCOL=1
      DO 90 K=1,NU
         IF (NCOL.GT.NEQ) GOTO 100
         P=NCOL
         AMAX=DABS(M(NCOL,K))
         DO 30 I=NCOL+1,NEQ
            IF (DABS(M(I,K)).GT.AMAX) THEN
               AMAX=DABS(M(I,K))
               P=I
            ENDIF
   30    CONTINUE

         IF (AMAX.GT.TOL) THEN
            IF (P.NE.NCOL) THEN
               DO 40 J=K,NU
                  TMP=M(NCOL,J)
                  M(NCOL,J)=M(P,J)
                  M(P,J)=TMP
   40          CONTINUE
            ENDIF

            DO 70 I=NCOL+1,NEQ
               FAC=M(I,K)/M(NCOL,K)
               M(I,K)=0.0D0
               DO 60 J=K+1,NU
                  M(I,J)=M(I,J)-FAC*M(NCOL,J)
   60          CONTINUE
   70       CONTINUE
            RANK=RANK+1
            NCOL=NCOL+1
         ENDIF
   90 CONTINUE

  100 RETURN
      END

C=======================================================================
C     WEIGHTED LEAST-SQUARES SOLVER USING NORMAL EQUATIONS AND GAUSSIAN
C     ELIMINATION WITH PARTIAL PIVOTING.
C
C     MINIMIZES SUM_K (W(K)*(A(K,:)*X-B(K)))**2.
C=======================================================================
      SUBROUTINE WLSOLVE(NEQ,NU,A,B,W,X,INFO)
      IMPLICIT NONE
      INTEGER MAXU,MAXQ
      PARAMETER (MAXU=40,MAXQ=140)
      INTEGER NEQ,NU,INFO,I,J,K,P
      DOUBLE PRECISION A(MAXQ,MAXU),B(MAXQ),W(MAXQ),X(MAXU)
      DOUBLE PRECISION NORM(MAXU,MAXU),RHS(MAXU)
      DOUBLE PRECISION AI,AJ,WB,AMAX,TMP,FAC,SUM

      INFO=0

      DO 20 I=1,MAXU
         RHS(I)=0.0D0
         X(I)=0.0D0
         DO 10 J=1,MAXU
            NORM(I,J)=0.0D0
   10    CONTINUE
   20 CONTINUE

C     FORM A^T W^2 A AND A^T W^2 B.
      DO 60 K=1,NEQ
         WB=W(K)*B(K)
         DO 50 I=1,NU
            AI=W(K)*A(K,I)
            RHS(I)=RHS(I)+AI*WB
            DO 40 J=1,NU
               AJ=W(K)*A(K,J)
               NORM(I,J)=NORM(I,J)+AI*AJ
   40       CONTINUE
   50    CONTINUE
   60 CONTINUE

C     GAUSSIAN ELIMINATION WITH PARTIAL PIVOTING.
      DO 130 K=1,NU-1
         P=K
         AMAX=DABS(NORM(K,K))
         DO 70 I=K+1,NU
            IF (DABS(NORM(I,K)).GT.AMAX) THEN
               AMAX=DABS(NORM(I,K))
               P=I
            ENDIF
   70    CONTINUE
         IF (AMAX.LE.1.0D-30) THEN
            INFO=K
            RETURN
         ENDIF

         IF (P.NE.K) THEN
            DO 80 J=K,NU
               TMP=NORM(K,J)
               NORM(K,J)=NORM(P,J)
               NORM(P,J)=TMP
   80       CONTINUE
            TMP=RHS(K)
            RHS(K)=RHS(P)
            RHS(P)=TMP
         ENDIF

         DO 120 I=K+1,NU
            FAC=NORM(I,K)/NORM(K,K)
            NORM(I,K)=0.0D0
            DO 100 J=K+1,NU
               NORM(I,J)=NORM(I,J)-FAC*NORM(K,J)
  100       CONTINUE
            RHS(I)=RHS(I)-FAC*RHS(K)
  120    CONTINUE
  130 CONTINUE

      IF (DABS(NORM(NU,NU)).LE.1.0D-30) THEN
         INFO=NU
         RETURN
      ENDIF

C     BACK SUBSTITUTION.
      DO 170 I=NU,1,-1
         SUM=RHS(I)
         DO 150 J=I+1,NU
            SUM=SUM-NORM(I,J)*X(J)
  150    CONTINUE
         X(I)=SUM/NORM(I,I)
  170 CONTINUE

      RETURN
      END
